### ISSUE TITLE
Condition Bug in JSON creation

### ISSUE THREAD

**Issue by cbizon** [clingen-data-model/clingen-interpretation#73] opened 2017-04-25 18:48 UTC
Found this in VarInterp274, looks like a mistake to me

```         
 "condition": [
            {
              "cg:id": "-"
            }
          ],
```

**Comment by bpow** [comment] 2017-04-26 00:17
Well, I'll chalk this up to "JSON creation working as intended". This is related, I think, to the discussion of benign variants being benign for every condition... or maybe no conditions.

The sheets have these "condition" attributes (A118) referring to "-", which gets interpreted as an ID. I would be in favor of not stating a condition for these CriterionAssessments (e.g., making condition an optional attribute)... or we could have a "condition" for "no condition" or "any condition".

Thoughts from @larrybabb ?

**Comment by larrybabb** [comment] 2017-04-26 13:31
This issue has caused lots of discussion between ClinGen and ClinVar.  I say we get Steven H to summarize the thinking at our meeting today.

I believe the answer will be that we do need to make this optional on VUS, LB and B interps (it is in the VCI to be sure).  And I believe it ties somewhat into the direction concept of the interpretation.

In some respects if the evidence points to pathogenicity at some level (even mildly uncertain - but in that direction), then you must have the context condition in which to frame that interpretation.

However, if you begin to interpret the "benign"-ness of a variant in the context of individual conditions, it creates a new kind of challenge.  

If in fact you are to say that the variant does not cause an impact on the gene product that would interrupt the function of that gene in any "pathogenic" manner then isn't it reasonable to say that it would be benign for any or all mendelian conditions?

Unfortunately, this "any" or "all" concept is challenging to code as well, since we have not truly identified the coding system that contains a concept within a hierarchy or ontology that would represent all conditions under which the ACMG guidelines would be constrained by.  If we had that, then we could potentially use that.

It also gets into the notion of having to list all the benign condition interpretations independently, even if there are one or more path direction interpretations for the same variant.

Currently, the presumption has been that if you state that a given variant is interpreted on the path direction for some disease then you do not have to explicitly state the benign impact on any of the other conditions that that same gene may be involved with.

There have been many more that are much more knowledgeable than I about this issue which have discussed and come to differing conclusions.

We should have Steven H. summarize the ClinGen (Heidi) v ClinVar position on this.

**Comment by larrybabb** [comment] 2017-04-26 13:32
For our near term, we should make "condition" optional and we can use the "-" in the id as a flag to clarify this or we could simply remove the condition reference from these interpretation concepts.

**Comment by larrybabb** [comment] 2017-04-26 13:37
This is timely.  A meeting this Friday where Heidi and Illumina's Alison Coffey will discuss this very topic in practice.

Hello,
 
Just a reminder for the ClinVar Community call this Friday April 28th at 12pm ET. Please find the agenda and WebEx information below.
 
April 28th ClinVar Community Call Agenda
Discussion Regarding Associating Conditions to Variants in ClinVar
Introduction (Heidi Rehm)
Illumina's process (Alison Coffey)
Time permitting Generating and Posting a List of Laboratories Meeting Minimum Requirements for Data Sharing to Support Quality Assurance (Heidi Rehm)
 
Thank you,
Danielle
 
 
ClinVar/ClinGen
12:00 pm  |  Eastern Standard Time (New York, GMT-05:00)  |  1 hr
 
 
 
Join WebEx meeting
 
Meeting number:	624 128 338
Meeting password:	clinvar
 
 
 
Join by phone
1-877-668-4493 Call-in toll-free number (US/Canada)
1-650-479-3208 Call-in toll number (US/Canada)
Access code: 624 128 338
Global call-in numbers  |  Toll-free calling restrictions

**Comment by bpow** [comment] 2017-05-05 16:20
Seems like this was addressed with making condition optional. Closing.

**Closed by bpow** 2017-05-05 16:20 UTC
